---
apiVersion: v1
kind: Service
metadata:
  name: docker-producer-svc-test
  labels:
    app: docker-producer-svc-test
spec:
  ports:
  - port: 12345
    name: server
  type: NodePort
  selector:
    app: docker-producer-svc-test
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: docker-producer-svc-test
spec:
  replicas: 1
  selector:
   matchLabels:
    app: docker-producer-svc-test
  template:
    metadata:
      labels:
        app: docker-producer-svc-test
    spec:
      tolerations:
      - key: "key"
        operator: "Equal"
        value: "value"
        effect: "NoSchedule"
#      nodeSelector:
#        zk: zk-3
      containers:
      - name: docker-producer
        imagePullPolicy: Always
        image: dockeryanxiao/docker-dubbo-producer:master
        resources:
         limits:
          cpu: "0.2"
          memory: "300Mi"
        ports:
        - containerPort: 12345
        env:
        - name: ZOOKEEPER_SERVER
          value: zookeeper://zk-2-svc
